case: slice380_down2

dataset:
  type: ST2D  # Can be set to "auto" for intelligent detection
  data_file: logs/GAE/${case}/lightning_logs/version_0/embedded-all.h5ad
  val_proportion: 0.2
  keep_ratio: True
  require_coordnorm: False

pipeline:
  target: embeddings

  inr:
    model: FFN
    num_hidden_layers: 3
    num_hidden_features: 2048 
    phase: 1000 # number of epoches in the INR pretraining phase, after this phase the decoder will be trained.
    decoder:
      ckpt: logs/GAE/${case}/lightning_logs/version_0/checkpoints/last.ckpt
      recon_loss: True
      finetune: True
      
  optimization:
    seed: 8848
    epochs: 2000
    lr: 1e-4
    val_freq: 200
    logs: logs/GAE+FFN/${case}
    batch_size: 5000
  
  predict_mode: no
  custom_coords_file: data/preprocessed_data/slice440_custom_coords.npy
  reconstructed_data: reconstructed-custom.h5ad